topic_avatars_size:
  default: 45
  type: enum
  choices:
    - 60
    - 70
    - 80
    - 90
    - 100
    - 120
    - 140
    - 160
    - 180
    - 200
  description:
    en: "Choose the avatar size on topics. Default value is 45px."
avatars_border_radius:
  default: 50%
  type: enum
  choices:
    - 0%
    - 10%
    - 20%
    - 30%
    - 40%
  description:
    en: "Choose the border-radius of the avatars on the site. The setting will be applied to all avatars, including the one on the header and the one on the user-card. 0% corresponds to a square shape, 50% to a rounded shape. Default value at 50%"    
latest_avatar_size:
  default: 45
  type: enum
  choices:
    - tiny
    - small
    - large
    - huge
    - medium
  description:
    en: "Choose the avatar size on latest. Default value is small."
