topic_avatars_size:
  default: 45
  type: enum
  choices:
    - 60
    - 70
    - 80
    - 90
    - 100
    - 120
    - 140
    - 160
    - 180
    - 200
 topic_avatars_border_radius:
  default: 50%
  type: enum
  choices:
    - 0%
    - 10%
    - 20%
    - 30%
    - 40%
