latest_avatar_size:
  default: small
  type: enum
  choices:
    - tiny
    - small
    - medium
    - large
    - extra_large
    - huge
  description:
    en: "Choose the avatar size on latest. Default value is small (25px). To see the changes applied, refresh the page with ctrl+F5 or cmd+shif+R."
topic_avatars_size:
  default: 45
  type: enum
  choices:
    - 45
    - 60
    - 70
    - 80
    - 90
    - 100
    - 120
    - 140
    - 160
    - 180
    - 200
  description:
    en: "Choose the avatar size on topics. Default value is 45px. To see the changes applied, refresh the page with ctrl+F5 or cmd+shif+R."
header_avatars_size:    
  default: 32
  type: enum
  choices:
    - 45
    - 60
    - 70
    - 80
    - 90
  description:
    en: "Choose the avatar size on header. Default value is 32px. To see the changes applied, refresh the page with ctrl+F5 or cmd+shif+R." 
header_height:
  default: 60
  type: enum
  choices:
    - 70
    - 80
    - 90
    - 100
  description:
    en: "Choose the height of the header. The choice must be made based on the header_avatars_size + 10px. For example, if the header_avatars_size is set to 90px, the header should be 100px. Default value is 60px."
avatars_border_radius:
  default: 50%
  type: enum
  choices:
    - 0%
    - 10%
    - 20%
    - 30%
    - 40%
  description:
    en: "Choose the border-radius of the avatars on the site. The setting will be applied to all avatars, including the one on the header and the one on the user-card. 0% corresponds to a square shape, 50% to a rounded shape. Default value at 50%"    
space_from_header:
  default: 82px
  type:enum
  choises:
    - 92
    - 102
    - 112
  description:
    en: "Choose the distance from the header. Default value at 82px"    
